services:
  proxy:
    image: nginx:latest
    ports:
      - '${AUTHENTICATION_APP_PORT}:80'
    volumes:
      - ./server/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
    networks:
      - passway-network
  auth:
    volumes:
      - ./server/authentication:/usr/src/app
    build:
      context: ./server/authentication
    expose:
      - 3000
    networks:
      - passway-network

networks:
  passway-network:
