services:
  proxy:
    ports: !reset
    networks:
      - passway-int-network

  api:
    environment:
      IS_INTEGRATION_TEST: true
    networks:
      - passway-int-network
    env_file:
      - .env
      - .env.integration-test

  db:
    ports: !reset []
    networks:
      - passway-int-network
    volumes:
      - /var/lib/postgresql/data

  cache:
    ports: !reset []
    networks:
      - passway-int-network

  sdk:
    ports: !reset []
    networks:
      - passway-int-network
    env_file:
      - .env
      - .env.integration-test

  content-store:
    ports: !reset []
    networks:
      - passway-int-network
    volumes:
      - ./server/content-storage/provision-minio.sh:/opt/provision-minio.sh:ro
    env_file:
      - .env
      - .env.integration-test

networks:
  passway-int-network:
