services:
  proxy:
    image: nginx:latest
    ports:
      - '${AUTHENTICATION_APP_PORT}:80'
    volumes:
      - ./server/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
    networks:
      - passway-network

  auth:
    build:
      context: ./server/authentication
    networks:
      - passway-network
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file: '.env'

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - passway-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: bitnami/valkey:7.2.5
    environment:
      VALKEY_PASSWORD: ${CACHE_PASSWORD}
      VALKEY_DATABASE: ${CACHE_NAME}
    ports:
      - '${CACHE_PORT}:6379'
    networks:
      - passway-network
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  passway-network:

volumes:
  db_data:
