services:
  proxy:
    image: nginx:latest
    ports:
      - '${AUTHENTICATION_APP_PORT}:80'
    volumes:
      - ./server/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
    networks:
      - passway-network

  auth:
    volumes:
      - ./server/authentication:/usr/src/app
    build:
      context: ./server/authentication
    expose:
      - 3000
    ports:
      - 9229:9229
    networks:
      - passway-network
    depends_on:
      db:
        condition: service_healthy
    env_file: '.env'

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - passway-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  passway-network:

volumes:
  db_data:
