services:
  auth:
    volumes:
      - ./server/authentication:/usr/src/app
    build:
      context: ./server/authentication
    ports:
      - '${AUTHENTICATION_APP_PORT}:${INTERNAL_AUTHENTICATION_APP_PORT}'
