services:
  proxy:
    ports: !reset
    networks:
      - passway-int-network

  api:
    environment:
      IS_INTEGRATION_TEST: true
    networks:
      - passway-int-network

  db:
    ports: !reset []
    networks:
      - passway-int-network
    volumes:
      - /var/lib/postgresql/data

  cache:
    ports: !reset []
    networks:
      - passway-int-network

  sdk:
    ports: !reset []
    networks:
      - passway-int-network

  content-store:
    ports: !reset []
    networks:
      - passway-int-network

networks:
  passway-int-network:
