name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build image
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test
          npm run test:integration
